### PR TITLE
:recycle: Use http_build_query() for building Auth Request body.

### LINKED ISSUE #13: Invalid authentication request
Many PHP OAuth clients require a request body in `x-www-form-urlencoded` type. In the case of `sendOauthRequest()` request is sent with `json_encode` and `application/json` Content-Type. I fixed this issue and will provide the PR.

### PR DESCRIPTION
**Pull request by ABGEO**
Fixes #13.

### CODE REVIEW

**Comment by ABGEO** [comment]
Hi @kielabokkie,

Anything new about this?

**Comment by kielabokkie** [comment]
@ABGEO Thanks for this PR and apologies for the delay. I think the change to `x-www-form-urlencoded` might cause some troubles for current users who haven't implemented the OAuth spec correctly so I'll tag it as version v3.0.0

**Comment by ABGEO** [comment]
@kielabokkie great decision.

**Comment by kielabokkie** [comment]
Just tagged it, let me know if you encounter any issues

**Pull request merged**
